server:
  port: 8189


spring:
  # JDBC properties
  datasource:
    url: jdbc:mariadb://localhost:3306/documentmgmt_db?useSSL=false&serverTimezone=UTC
    username: root
    password: smart
    ddl-auto: none
  #multipart configuration
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      file-size-threshold: 2KB
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect=org:
          hibernate:
            dialect: MariaDBDialect